_target_: nncert.lightning.modules.ImageClassifier

clf:
  _target_: torch.hub.load
  repo_or_dir: chenyaofo/pytorch-cifar-models
  model: cifar10_resnet20
  pretrained: false

num_classes: ${dataset.num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${training.epochs}
